### PR TITLE
Add newer hOS prebuilds to default/example app replace list

### PR DESCRIPTION
**Pull request by Rev4N1**
In the lastest update "hentaiLewdbSVTDummy" was removed and those 2 were added.

Probably good to keep the old one for compatibility with older versions.

### CODE REVIEW

**Comment by osm0sis** [comment]
So there ROM that was called hentaiOS is now called helluvaOS?

**Comment by Rev4N1** [comment]
Yes, hentaiOS and helluvaOS are the same ROM, they are rebranding.

Good catch, it was 4am while a was doing the PR 
I just checked some of the other pixels series ROM:
Oriole has helluvaProductDeviceRaviole.
Cheetah has helluvaProductDevice.
Husky has helluvaProductDevice.
They all have the helluvaProductSecretStub one.

Be aware that there is also hOS for some Xiaomi devices and they might have different names in the future, but i cannot check right now as the update is not shipped for Xiaomi, only for Pixel.

Just to provide some information:
helluvaProductSecretStub is the package that they provide for you to update via apk.
But atleast on oriole just by disabling the helluvaProductDeviceRaviole, PIF is working whatever you have the SecretStub apk installed or not. So I leave up to you to disable it or not.

**Comment by Rev4N1** [comment]
There i fixed it if you want to push

**Comment by osm0sis** [comment]
Yeah looks great! Thanks!

**Pull request merged**
