### PR TITLE
Add additional PixelPropsUtils props to workaround

### PR DESCRIPTION
**Pull request by bphd**

### CODE REVIEW

**Comment by osm0sis** [comment]
Unnecessary

**Comment by bphd** [comment]
> Seems unnecessary, .pi is the one that matters.

Can tell you that on my CROM if I don't touch these very properties, my CROM continues to push its own dead fingerprint. It's absolutely necessary

**Comment by osm0sis** [comment]
Oh weird, I was just going on what @joeyhuab told me. Maybe things have further deviated from there. 🤔

**Comment by osm0sis** [comment]
@bphd Is the .gapps one for certain necessary in your setup? Seems like .pi and .gms would cover it where we only ever spoof to GMS.

**Comment by bphd** [comment]
> @bphd Is the .gapps one for certain necessary in your setup? Seems like .pi and .gms would cover it where we only ever spoof to GMS.

Idk really. Tested with both as it was already a big journey enough to debug my way out. Cross testing that would have been even heavier

You have two choice, either apply both of them and wait for user complain to have lost functionalities to revert (but I lost none on my part). Either apply one of them and user will still think that PIFF don't patch their case and wouldn't know how to help themselves (because it's honestly not obvious to find such properties, so maybe applying them both would take a thorn out of one's foot that they wouldn't be able to do themselves)

Personally I suggest the former, it's really not that big of a risk for a sure reward

**Comment by osm0sis** [comment]
You can't just quickly test it without the .gapps entry on your setup?

**Comment by bphd** [comment]
> You can't just quickly test it without the .gapps entry on your setup?

It's not quick, so can't be done "quickly", and no I can't test, I switched CROM

**Comment by osm0sis** [comment]
@bphd What ROM was the behavior you were seeing on, by the way? I'd like to recreate it and check some things in the logs. 👍

**Comment by bphd** [comment]
> @bphd What ROM was the behavior you were seeing on, by the way? I'd like to recreate it and check some things in the logs. 👍

Old version of Matrixx. But it still is in operation on many CROM latest version. You can figure out where it still is operative simply by searching such properties on GitHub. Repositories where it still hasn't changes still is in effect. But as of today, new variable are used but the problem remains the same for CROM that still try to inject FP/KB by themselves or tweak properties where not needed. Or worse, refuse any Google attestation and call it a day, that less to support ig

**Comment by osm0sis** [comment]
Thanks, what version though? My point was some versions of PPU will work with what I had in the first place and some will only work after what you've added, so I want to make sure I'm using the exact one you had.

**Comment by osm0sis** [comment]
I tried official Matrixx builds for hotdogb from here: https://sourceforge.net/projects/projectmatrixx/files/Android-14/hotdogb/

Went through v10.5.3, v10.6.2, v10.7.3, v10.8.1, v10.9.0, v10.9.1 and v10.10.0 and I don't see any of the persist.sys.pixelprops.* props in question from our commits here. 🤔

**Comment by bphd** [comment]
> by searching such properties on GitHub

**Comment by osm0sis** [comment]
Sure, but it's pretty frustrating playing 20 questions with you and then having to do my own research when you've already got the answer..

**Comment by osm0sis** [comment]
I'm also surprised this commit worked for you at all since after searching GitHub as you suggested I don't see a single instance of both resetprop -n -p persist.sys.pixelprops.pi and persist.sys.pixelprops.gapps/persist.sys.pixelprops.gms being in the same version of PPU... 🤔

Anyway, found an old version of crDroid for one of my devices that should have gms/gapps props per their commit history, so I'll get it working. 😉

https://github.com/crdroidandroid/android_frameworks_base/blob/14.0-20240706/core/java/com/android/internal/util/crdroid/PixelPropsUtils.java#L38

**Pull request merged**
