### PR TITLE
module/action: don't sleep on MMRL action

### PR DESCRIPTION
**Pull request by backslashxx**
This is an upcoming feature on MMRL.
It also exits "paused"
juts like magisk, so we don't need to sleep here

https://github.com/user-attachments/assets/f8a3ea4a-3bae-46bf-b125-2106846544ee

printenv dump
[printenv.txt](https://github.com/user-attachments/files/18140126/printenv.txt)

### CODE REVIEW

**Comment by osm0sis** [comment]
Then it would be && MMRL != true

**Comment by backslashxx** [comment]
i accidentally deleted the repo, but apatch also shares the same behavior as ksu now

**Comment by backslashxx** [comment]
https://github.com/bmax121/APatch/commit/c44c226afc3e56b90b8ccf6cce3b708f3c2440be

apatch acts just like ksu now, but yeah I thought about it, its not on stable version yet, CI only

just disregard this pr

**Comment by DerGoogler** [comment]
MMRL uses now busybox when the option is toggled for shell

**Comment by osm0sis** [comment]
@DerGoogler, if you want the env to match the root managers you'll also want ASH_STANDALONE=1 before running the busybox shell.

**Comment by DerGoogler** [comment]
Good to know. I'll add that the next days 👍

**Comment by backslashxx** [comment]
as for that logic

-z MAGISKTMP and -z MMRL

the issue is that you can have

ksu with mmrl
apatch with mmrl
magisk with mmrl

so youll have to guess the environment instead.

currenlty only magisk and mmrl does that "pause" when script is done exiting.
even apatch is doing it like ksu now so you have to add a delay on that.
this is what im doing here https://github.com/backslashxx/bindhosts/blob/master/module/action.sh#L22

**Comment by osm0sis** [comment]
Magisk doesn't do the pause anymore, they removed it a couple canaries before final v28.1, so I have a few commits ago as well: 
https://github.com/osm0sis/PlayIntegrityFork/commit/c635a9e3ba7b91e380f26ca9b52ac4f9192d63b0

APatch never auto-closed if successful previously, has that changed?

**Comment by backslashxx** [comment]
> APatch never auto-closed if successful previously either, has that changed?

yes
 
> If so, `[ "$KSU" = true -o "$APATCH" = true ] && [ "$MMRL" != true ]` seems like the obvious way to go here, not sure why you're messing with checks for $MAGISKTMP.

yeah, for what we are trying to achieve,
[ "$KSU" = true -o "$APATCH" = true ]  functions essentially like  -z MAGISKTMP since that envvar does NOT exist on the env  of those managers.

same for [ "$MMRL" !=  true ], mmrl envvar wont be on those managers.
its just shorter logic
though yeah if its about maintainability due to it being weird to you sure

**Comment by osm0sis** [comment]
Yup, I prefer to check for true just in case something starts declaring them as false at some point. 👍

**Pull request closed without merging**
