### PR TITLE
Fix SELinux prop spoofing

### PR DESCRIPTION
**Pull request by salvogiangri**
Using `resetprop --delete` will trigger ro property manipulation detection.

### CODE REVIEW

**Comment by osm0sis** [comment]
That's better than detection based on its existence at all. Did you read the comment you removed?

**Comment by salvogiangri** [comment]
I assumed `ro.build.selinux` shouldn't have a different value than 1 considering other props/sysfs node gets spoofed aswell.
Is there a case where this prop has a different value than 1 in user images that ship SELinux support? Or cases where using a different value than stock breaks any verdicts?

**Comment by osm0sis** [comment]
topjohnwu was the one who decided it was better to delete it in the first place due to the different OEMs having different values for enforcement, per my documentation in the comment. What app are you testing property manipulation detection with?

**Comment by salvogiangri** [comment]
> What app are you testing property manipulation detection with?

I'm using latest NativeTest. Had the same property manipulation detection in my custom ROM and after removing some `resetprop --delete` calls some users reported their banking apps started to work again.

**Comment by osm0sis** [comment]
Right, well it's a case of "can't win em all" because some apps detect ro.build.selinux 1 as bad and some detect ro.build.selinux 0 as bad, then if we remove it with --delete some also detect the removal as bad. 🤷‍♂️

**Comment by osm0sis** [comment]
Fixed by cd32f0c

**Pull request closed without merging**
