### PR TITLE
Check for busybox executable in any $PATH locations instead of using a specific location

### PR DESCRIPTION
**Pull request by betterphp**

### CODE REVIEW

**Comment by osm0sis** [comment]
Anything on $PATH is already handled here: 
https://github.com/osm0sis/PlayIntegrityFork/blob/main/module/autopif.sh#L17

**Comment by betterphp** [comment]
Only for `wget` - I had busybox but no wget.

**Comment by betterphp** [comment]
I had to patch this script on my device to get it to work, not just making this change for the fun of it :P

**Comment by osm0sis** [comment]
Right, but if busybox is on the $PATH then so is wget.

**Comment by betterphp** [comment]
image

I'm not making it up...

**Comment by betterphp** [comment]
image

**Comment by osm0sis** [comment]
My busybox installer would never exclude an applet symlink unless the ROM has one already. 🤔

**Comment by osm0sis** [comment]
It prefers /system/xbin, but if that doesn't exist it uses /system/bin and filters out any existing applets so that it doesn't replace ROM ones.

**Comment by betterphp** [comment]
Ah okay that makes sense. I have `/system/bin` with a handful of links

image

and no `/system/xbin` directory at all.

**Comment by osm0sis** [comment]
That's very weird... Uninstall busybox, reboot, reinstall busybox and give me the log?

**Comment by betterphp** [comment]
There's not really much to the installation log if that's the one you're after?

```
- Copying zip to temp directory
- Installing UPDATE-Busybox.Installer.v1.36.1-ALL-signed.zip
Archive:  /data/user/0/ccnujo.s/cache/flash/install.zip
  inflating: customize.sh
Archive:  /data/user/0/ccnujo.s/cache/flash/install.zip
  inflating: diffusion_config.sh
  inflating: module.prop

Busybox Installer Script
by osm0sis @ xda-developers

Mounting...

Extracting files...
Archive:  /data/user/0/ccnujo.s/cache/flash/install.zip
  inflating: META-INF/com/google/android/updater-script
  inflating: META-INF/com/google/android/update-binary
  inflating: README.md
  inflating: busybox-arm
  inflating: busybox-arm-selinux
  inflating: busybox-arm64
  inflating: busybox-arm64-selinux
  inflating: busybox-mips
  inflating: busybox-mips64
  inflating: busybox-x86
  inflating: busybox-x86-selinux
  inflating: busybox-x86_64
  inflating: busybox-x86_64-selinux
  inflating: customize.sh
  inflating: diffusion_config.sh
  inflating: module.prop
  inflating: META-INF/MANIFEST.MF
  inflating: META-INF/CERT.SF
  inflating: META-INF/CERT.RSA

Installing...
Using architecture: arm64-selinux
Using path: /data/adb/modules_update/busybox-ndk/system/bin

Cleaning...

Creating symlinks...

Unmounting...

Done!
```

**Comment by betterphp** [comment]
It hangs for a second or some before "?Unmounting..." so that might mean something.

`busybox --list` does list everything (including wget)

Realising this is probably something I've done somehow now :P

**Comment by osm0sis** [comment]
I guess check the symlinks again

**Comment by betterphp** [comment]
After rebooting they were still just those few from before.

So I tried copying the script you linked and adding

```
XBIN="/system/bin

custom_postinstall
```
to the bottom.

That created them all successfully.

No idea, probably just close this - obviously it's not actually a change that's needed in the end :P

**Comment by betterphp** [comment]
The only thing I did recently was switch from Kitsune Mask 27001 to Magisk 27006 and install TrickyStore.

In the past I had used your autopif.sh script without having to install busybox first.

It's working now so I'm happy to drop it :P Feel free to ask for anything though if it's bothering you now :P

**Comment by osm0sis** [comment]
This should take care of it for now 🙌

https://github.com/osm0sis/PlayIntegrityFork/commit/2857e3d2f8dc11c353aa726654957fedd3fec318

**Pull request closed without merging**
