### PR TITLE
Update example.pif.json

### PR DESCRIPTION
**Pull request by V0latyle**
Add advanced settings with explanation of each function.

### CODE REVIEW

**Comment by osm0sis** [comment]
Thanks, but Advanced Settings are only for advanced users so intentionally left out of the template. They're described in the README for everyone.

**Comment by rustamlabs** [comment]
Not directly related but..
Can we parametrize advanced configuration in migrate.sh? such as `migate.sh -f -a 11100 in-pif.json out-pif.json` instead of changing values in the script manually?
That would make it easier to test multiple configurations. However this will not support having default argument for -a as in-file and out-file arguments are positional. If you agree I can create the PR.

**Comment by osm0sis** [comment]
The way I currently have it maintain the config from the existing custom.pif.json seems good enough to me.

**Comment by pershoot** [comment]
@rustamlabs One-liner it.
For example:
sed -i.BK -e 's/"spoofProps": .*"/"spoofProps": '\"0\"'/' custom.pif.json && sh killgms.sh

**Pull request closed without merging**
