### PR TITLE
Use unique project name

### PR DESCRIPTION
**Pull request by aviraxp**
This also works around a shamiko bug which will be fixed later.

### CODE REVIEW

**Comment by osm0sis** [comment]
Thanks so much!

Would it be worth changing it back later once the Shamiko fix is out to see if there are any other issues going forward?

**Comment by osm0sis** [comment]
Also, would making it playintegrityfork still work with latest Shamiko, or is there special handling in place for specifically playintegrityfix projects that it would be better to stick with?

**Comment by aviraxp** [comment]
Just keep it as is for now.

**Comment by osm0sis** [comment]
Cool, good to know. Thanks again! 👍

**Pull request merged**
