### PR TITLE
Extend spoof mechanisms beyond GMS thanks to target.txt

### PR DESCRIPTION
**Pull request by bphd**

### CODE REVIEW

**Comment by bphd** [comment]
> No.. sorry, but modifying Tricky Store

Not what is meant at all. That file is meant to target PIF abilities alone

> If someone wants WhatsApp on TS's list they can add it.

Yeah, on TS target, not what is meant here at all. Here it's PIFF target

**Comment by osm0sis** [comment]
Ah, you'll need an awful lot more code then, since target.txt isn't a thing in the PIF codebase.

**Comment by bphd** [comment]
> Ah, you'll need an awful lot more code then, since target.txt isn't a thing in the PIF codebase.

I allowed edits by maintainers

**Comment by osm0sis** [comment]
If you want a feature via PR, you code it.

**Comment by bphd** [comment]
> > I allowed edits by maintainers
> 
> You can't just make a random useless file and expect someone else to do literally all of the work for you. If you want a feature via PR, you code it.

There is no issues section

**Comment by osm0sis** [comment]
> There is no issues section

That's no excuse. You want to make a suggestion you can ask in my xda thread.

**Pull request closed without merging**
